@extends('layouts.admin')

@section('title', 'Edit News Category')

@section('content')
<div class="admin-header">
    <div>
        <h1 class="admin-title">Edit News Category</h1>
        <p class="admin-subtitle">Update category information</p>
    </div>
    <a href="{{ route('admin.news-categories.index') }}" class="btn btn-secondary">
        <svg class="btn-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
        </svg>
        Back to Categories
    </a>
</div>

<div class="ios-card">
    <form action="{{ route('admin.news-categories.update', $newsCategory) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name" class="form-label required">Category Name</label>
            <input 
                type="text" 
                id="name" 
                name="name" 
                class="form-input @error('name') is-invalid @enderror" 
                value="{{ old('name', $newsCategory->name) }}"
                required
                autofocus
            >
            @error('name')
                <span class="form-error">{{ $message }}</span>
            @enderror
            <span class="form-hint">The display name for this category</span>
        </div>

        <div class="form-group">
            <label for="slug" class="form-label">Slug</label>
            <input 
                type="text" 
                id="slug" 
                name="slug" 
                class="form-input @error('slug') is-invalid @enderror" 
                value="{{ old('slug', $newsCategory->slug) }}"
            >
            @error('slug')
                <span class="form-error">{{ $message }}</span>
            @enderror
            <span class="form-hint">URL-friendly version (leave empty to auto-generate from name)</span>
        </div>

        <div class="form-group">
            <label for="description" class="form-label">Description</label>
            <textarea 
                id="description" 
                name="description" 
                rows="4" 
                class="form-input @error('description') is-invalid @enderror"
            >{{ old('description', $newsCategory->description) }}</textarea>
            @error('description')
                <span class="form-error">{{ $message }}</span>
            @enderror
            <span class="form-hint">Optional description for this category</span>
        </div>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">
                <svg class="btn-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
                </svg>
                Update Category
            </button>
            <a href="{{ route('admin.news-categories.index') }}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>

@if($newsCategory->news()->count() > 0)
<div class="ios-card mt-6">
    <div class="card-header">
        <h3 class="card-title">Associated News Articles</h3>
        <span class="badge badge-info">{{ $newsCategory->news()->count() }} articles</span>
    </div>
    <div class="card-body">
        <p class="text-secondary">This category is used by {{ $newsCategory->news()->count() }} news article(s). Deleting this category will require reassigning these articles first.</p>
    </div>
</div>
@endif

@push('scripts')
<script>
    // Auto-generate slug from name
    const originalSlug = '{{ $newsCategory->slug }}';
    document.getElementById('name').addEventListener('input', function(e) {
        const slugInput = document.getElementById('slug');
        if (slugInput.value === originalSlug || slugInput.dataset.autoGenerated) {
            const slug = e.target.value
                .toLowerCase()
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/^-+|-+$/g, '');
            slugInput.value = slug;
            slugInput.dataset.autoGenerated = 'true';
        }
    });

    document.getElementById('slug').addEventListener('input', function() {
        if (this.value !== originalSlug) {
            delete this.dataset.autoGenerated;
        }
    });
</script>
@endpush
@endsection
